apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ${CI_PROJECT_NAME}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ${CI_PROJECT_NAME}
  minReplicas: 2
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
