apiVersion: v1
kind: Service
metadata:
  name: ${CI_PROJECT_NAME}
  annotations:
    prometheus.io/scrape: 'false'
spec:
  type: ClusterIP
  ports:
    - name: ${CI_PROJECT_NAME}
      port: 8080
  selector:
    app: ${CI_PROJECT_NAME}
